// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2cERKY9g7aI4V-jWzz7IRW3sxbeHFBcA',
    appId: '1:166979321802:web:1afded351929538468d933',
    messagingSenderId: '166979321802',
    projectId: 'testesegunranca',
    authDomain: 'testesegunranca.firebaseapp.com',
    databaseURL: 'https://testesegunranca.firebaseio.com',
    storageBucket: 'testesegunranca.firebasestorage.app',
    measurementId: 'G-66QNEP909M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rqR5GmB42STeU8xgbrwJGGtunCbsT6k',
    appId: '1:166979321802:android:0bef6ef8315a6ce068d933',
    messagingSenderId: '166979321802',
    projectId: 'testesegunranca',
    databaseURL: 'https://testesegunranca.firebaseio.com',
    storageBucket: 'testesegunranca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbW_zTC0mf4HE0cjbzU5pB7Ex4ndqxiY',
    appId: '1:166979321802:ios:595865f23559feae68d933',
    messagingSenderId: '166979321802',
    projectId: 'testesegunranca',
    databaseURL: 'https://testesegunranca.firebaseio.com',
    storageBucket: 'testesegunranca.firebasestorage.app',
    iosBundleId: 'com.example.virtualDisplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPbW_zTC0mf4HE0cjbzU5pB7Ex4ndqxiY',
    appId: '1:166979321802:ios:8814c12eca23cf0c68d933',
    messagingSenderId: '166979321802',
    projectId: 'testesegunranca',
    databaseURL: 'https://testesegunranca.firebaseio.com',
    storageBucket: 'testesegunranca.firebasestorage.app',
    iosBundleId: 'com.virtualDisplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2cERKY9g7aI4V-jWzz7IRW3sxbeHFBcA',
    appId: '1:166979321802:web:5d4dab5f45dacb5168d933',
    messagingSenderId: '166979321802',
    projectId: 'testesegunranca',
    authDomain: 'testesegunranca.firebaseapp.com',
    databaseURL: 'https://testesegunranca.firebaseio.com',
    storageBucket: 'testesegunranca.firebasestorage.app',
    measurementId: 'G-7JMZ4TN6E0',
  );
}
